/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_a4over6_MyVpnService */

#ifndef _Included_com_example_a4over6_MyVpnService
#define _Included_com_example_a4over6_MyVpnService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_a4over6_MyVpnService
 * Method:    vpn_entry
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_example_a4over6_MyVpnService_vpn_1entry
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
